spring.application.name=core-backend
# Server Port
server.port=8080

# Supabase PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.fgpcpmlilpbuliwmhgah
spring.datasource.password=Spotitifucan
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA Settings
# 'update' tells Java to automatically create the tables in Supabase based on your Issue.java file!
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Gmail SMTP — Community Confirmation Emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shyxark@gmail.com
spring.mail.password=eplj zkdm zfqa rdf
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Base URL for confirmation links in emails
app.base-url=http://localhost:8080